# Generated by Django 5.1.6 on 2025-03-03 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, help_text='Enter your first name', max_length=100, null=True)),
                ('Last_Name', models.CharField(blank=True, help_text='Enter your last name', max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, help_text='Enter your email', max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, help_text='Enter your image', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['First_Name', 'Last_Name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, help_text='Enter your category name', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['Category_Name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(blank=True, help_text='Enter your post title', max_length=100, null=True)),
                ('Post_Content', models.TextField(blank=True, help_text='Enter your post content', null=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini.author')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['Post_Title'],
            },
        ),
    ]
